### ISSUE TITLE
Add ability to start up without cammart and virtual environment enabled

### ISSUE THREAD

**Issue by dylanmcreynolds** [synchrotrons/Xi-cam.core#7]
At some beamlines, software installation limits having local and writable directories. This will create issues for xi-cam's cammart functionality. On first run, xi-cam creates a virtual environment that is used to install plugins. 

We will need to create a method to startup xi-cam without creating the virtual environment and without cammart for such installations.

One though would be to add a command line argument for xi-cam that is read to turn off these features.

**Comment by ronpandolfi** [comment]
The following PRs address this issue:
https://github.com/synchrotrons/Xi-cam.plugins/pull/15
https://github.com/synchrotrons/Xi-cam.gui/pull/22

**Comment by tacaswell** [comment]
What is the motivation for moving it from xicam.plugins -> xicam.gui?

I approved both, not sure what your merge policies on xi-cam are.
